CREATE DATABASE DataXuongMay
GO
USE DataXuongMay
GO
CREATE FUNCTION dbo.AUTO_IDNV()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaNV) FROM NHANVIEN) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaNV, 4)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'NV000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'NV00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'NV0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'NV' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

CREATE TABLE NHANVIEN
(
     MaNV NVARCHAR(20) CONSTRAINT IDNV DEFAULT dbo.AUTO_IDNV() PRIMARY KEY,
	 HoTen NVARCHAR(100) DEFAULT N'Empty',
	 SDT NVARCHAR(30) DEFAULT N'Empty',
	 PhanLoai NVARCHAR(100) DEFAULT N'Nhân viên lương cứng',
	 ToDoi NVARCHAR(50) DEFAULT N'Empty',
	 Luong INT DEFAULT 0
)
GO

CREATE FUNCTION dbo.AUTO_IDSP()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaSP) FROM SANPHAM) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaSP, 4)) FROM SANPHAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'SP000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'SP00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'SP0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'SP' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE SANPHAM
(
     MaSP NVARCHAR(20)  CONSTRAINT IDSP DEFAULT dbo.AUTO_IDSP() PRIMARY KEY,
	 TenSP NVARCHAR(100) DEFAULT N'Empty',
	 AnhURL NVARCHAR(300)  DEFAULT N'Empty',
	 Mau NVARCHAR(max) DEFAULT N'Empty',
	 Size NVARCHAR(max) DEFAULT N'Empty',
	 TonKho INT DEFAULT 0,
	 GhiChu NVARCHAR(Max)  DEFAULT N'Empty'
)
GO
CREATE FUNCTION dbo.AUTO_IDKH()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaKH) FROM KHACHHANG) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaKH, 4)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'KH000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'KH00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'KH0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'KH' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE KHACHHANG
(
     MaKH NVARCHAR(20)  CONSTRAINT IDKH DEFAULT dbo.AUTO_IDKH() PRIMARY KEY,
	 TenKH NVARCHAR(100) DEFAULT N'Empty',
	 SDT NVARCHAR(30) DEFAULT N'Empty',
	 DiaChi NVARCHAR(200) DEFAULT N'Empty'
)
GO
CREATE FUNCTION dbo.AUTO_IDDH()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaDH) FROM DONHANG) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaDH, 4)) FROM DONHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'DH000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'DH00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN N'DH0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999 THEN N'DH' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE DONHANG
(
     MaDH NVARCHAR(20)  CONSTRAINT IDDH DEFAULT dbo.AUTO_IDDH() PRIMARY KEY,
	 MaKH NVARCHAR(20) ,
	 NgayDat DATETIME ,
	 NgayHenGiao DATETIME ,
	 NgayGiao NVARCHAR(50) DEFAULT N'Empty' ,
	 TongTien INT DEFAULT 0,
	 TrangThai NVARCHAR(200) DEFAULT N'Chưa hoàn thành'
)
GO
CREATE FUNCTION dbo.AUTO_IDCTDH()
RETURNS NVARCHAR(20)
AS
BEGIN
	DECLARE @ID NVARCHAR(20)
	IF (SELECT COUNT(MaCTDH) FROM CT_DONHANG) = 0
		SET @ID = N'0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaCTDH, 4)) FROM CT_DONHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN N'CT000' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'CT00' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'CT0' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN N'CT' + CONVERT(NVARCHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
CREATE TABLE CT_DONHANG
(
     MaCTDH NVARCHAR(20) CONSTRAINT IDCTDH DEFAULT dbo.AUTO_IDCTDH() PRIMARY KEY,
	 MaDH NVARCHAR(20) ,
	 MaSP NVARCHAR(20) ,
	 Size NVARCHAR(50),
	 DonGia INT DEFAULT 0,
	 Mau NVARCHAR(50),
	 SoLuongDat INT DEFAULT 0,
	 SoLuongGiao INT DEFAULT 0,
	 ChiPhiThoMay INT DEFAULT 0,
	 GhiChu NVARCHAR(Max)  DEFAULT N'Empty'
)
GO
CREATE TABLE PHANCONG
(
     MaPC INT IDENTITY  PRIMARY KEY,
	 MaSP NVARCHAR(20) ,
	 MaNV NVARCHAR(20) ,
	 TienCong1SP INT DEFAULT 0,
	 SoLuongPhanCong INT DEFAULT 0,
	 SoLuongHoanThanh INT DEFAULT 0,
	 SoLuongCon INT DEFAULT 0,
	 GhiChu NVARCHAR(MAX) DEFAULT N'Empty',
	 TrangThai NVARCHAR(100) DEFAULT N'Chưa hoàn thành'
)
GO
CREATE TABLE CHIPHIVATTU
(
     MaCP INT IDENTITY  PRIMARY KEY,
	 MaD NVARCHAR(20) ,
	 TenCP NVARCHAR(50),
	 PhanLoai NVARCHAR(50),
	 SoTien INT DEFAULT 0,
	 GhiChu NVARCHAR(MAX) DEFAULT N'Empty'
)
GO
CREATE TABLE DANGNHAP
(
     TaiKhoan NVARCHAR(50)  PRIMARY KEY,
	 MatKhau NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE CHIPHIRIENG
(
     MaCP INT IDENTITY  PRIMARY KEY,
	 TenCP NVARCHAR(50),
	 PhanLoai NVARCHAR(50),
	 SoTien INT DEFAULT 0,
	 NgayChi DATETIME DEFAULT GETDATE(),
	 GhiChu NVARCHAR(MAX) DEFAULT N'Empty'
)
GO
CREATE TABLE THUCHI
(
     Ma INT IDENTITY  PRIMARY KEY,
	 Loai NVARCHAR(100),
	 MaNoi NVARCHAR(20) DEFAULT N'',
	 NoiDung NVARCHAR(200),
	 SoTien INT DEFAULT 0,
	 ThoiGian DateTime DEFAULT GETDATE()
)
GO
SELECT*FROM THUCHI

